### ISSUE TITLE
python 3.8 ast compability

### ISSUE THREAD

**Issue by roch1990** [roch1990/peon#38]
at python 3.7 - all is ok
python 3.8:
```
AttributeError: module '_ast' has no attribute 'Str'
```

**Comment by roch1990** [comment]
Similar to this:
https://github.com/pythonql/pythonql/issues/19

**Comment by vaibhav-ntnx** [comment]
When this issue will be fixed. Also can you tell me till what version of python i can use to avoid this issue

**Comment by roch1990** [comment]
Hi. You can use python 3.6/3.7
Also - if you need this feature, i can fix that in couple of weeks.

**Comment by roch1990** [comment]
@vaibhav-ntnx done
